name: Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for semantic-version to analyze all history
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: 5.x
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.10.2
      id: gitversion

    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --configuration Release --no-restore
    - name: Pack NuGet package
      # Use the version determined by semantic-version
      run: |
        dotnet pack KaspiShopClient.nuspec --configuration Release --output . /p:Version=${{ steps.gitversion.outputs.SemVer }}
    - name: Publish NuGet package
      # Only publish if a new version was generated
      if: steps.gitversion.outputs.CommitsSinceVersionSource != '0'
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate